name: make lint
on: push
jobs:
  my-job:
    runs-on: ubuntu-latest  
    steps:
    - uses: actions/checkout@v2
    
    - name: install poetry
      run: pip install --user poetry
    
    - name: install flake8
      run: python3 -m pip install flake8
      
    - name: lint
      run: make lint
